version: "3.8"
services:
  backend:
    build: ./backend
    container_name: golang_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=myuser
      - DB_PASSWORD=newpassword
      - DB_NAME=mydatabase

  frontend:
    build: ./frontend/my-app
    container_name: react_frontend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
