// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs
import (
    "log"
    "github.com/swaggo/swag"
    "os"
)
func loadSwaggerDoc() string {
	data, err := os.ReadFile("docs/swagger.json")
	if err != nil {
		log.Fatalf("Error reading swagger.json: %v", err)
	}
	return string(data)
}

var docTemplate = loadSwaggerDoc()

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Taskflow swagger",
	Description:      "Taskflow swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
