// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/message": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Test"
                ],
                "summary": "Test API",
                "responses": {
                    "200": {
                        "description": "Hello from Go backend!",
                        "schema": {
                            "$ref": "#/definitions/main.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/sprint": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Sprint"
                ],
                "summary": "Get all sprints",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/model.Sprint"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Hello from Go backend!"
                }
            }
        },
        "model.EventDate": {
            "type": "object",
            "properties": {
                "plan_time": {
                    "type": "string",
                    "example": "2025-3-21T00:00:00Z"
                },
                "retro_time": {
                    "type": "string",
                    "example": "2025-3-21T00:00:00Z"
                },
                "test_time": {
                    "type": "string",
                    "example": "2025-3-21T00:00:00Z"
                }
            }
        },
        "model.Sprint": {
            "type": "object",
            "required": [
                "end_date",
                "event_date",
                "name",
                "start_date"
            ],
            "properties": {
                "end_date": {
                    "type": "string",
                    "example": "2025-3-21T00:00:00Z"
                },
                "event_date": {
                    "$ref": "#/definitions/model.EventDate"
                },
                "name": {
                    "type": "string",
                    "example": "ver2.55"
                },
                "start_date": {
                    "type": "string",
                    "example": "2025-3-09T00:00:00Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Taskflow swagger",
	Description:      "Taskflow swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
