definitions:
  main.MessageResponse:
    properties:
      message:
        example: Hello from Go backend!
        type: string
    type: object
  model.Sprint:
    properties:
      end_date:
        example: "2025-03-21T00:00:00Z"
        type: string
      name:
        example: ver2.55
        type: string
      plan_date:
        example: "2025-03-21T00:00:00Z"
        type: string
      retro_date:
        example: "2025-03-21T00:00:00Z"
        type: string
      start_date:
        example: "2025-03-09T00:00:00Z"
        type: string
      test_date:
        example: "2025-03-21T00:00:00Z"
        type: string
    required:
    - end_date
    - name
    - start_date
    type: object
host: localhost:8080
info:
  contact: {}
  description: Taskflow swagger
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Taskflow swagger
  version: "1.0"
paths:
  /api/message:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Hello from Go backend!
          schema:
            $ref: '#/definitions/main.MessageResponse'
      summary: Test API
      tags:
      - Test
  /api/v1/sprint:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Sprint'
      summary: Delete a sprint
      tags:
      - Sprint
    get:
      parameters:
      - description: verison
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Sprint'
      summary: Get all sprints
      tags:
      - Sprint
    post:
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            additionalProperties: true
            type: object
      summary: Create a sprint
      tags:
      - Sprint
    put:
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/model.Sprint'
      summary: Update a sprint
      tags:
      - Sprint
swagger: "2.0"
