name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push frontend image
      run: |
        echo "NEXT_PUBLIC_API_HOST=${{ secrets.API_URL }}" > .env.local
        IMAGE_NAME=fxzfrog/nextjs_frontend
        docker build ./frontend -f ./frontend/Dockerfile -t $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest

    - name: Build and push backend image
      run: |
        IMAGE_NAME=fxzfrog/golang_backend
        docker build ./backend -f ./backend/Dockerfile -t $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
